name: CI

on:
  push:
    branches: [ main ] # Change 'main' to your default branch name if different

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests
        run: mvn test
